services:
  dapp:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: go_app
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: db
      ENDPOINT: http://hardhat:8545
    ports:
      - "8080:8080"
    restart: on-failure
  hardhat:
    build:
      context: ../
      dockerfile: ./hardhat/Dockerfile
    container_name: hardhat_node
    ports:
      - "8545:8545"
    restart: on-failure
